### ISSUE TITLE
OSB cluster migration in progress

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/ServiceStatus#2]
The complete OSBv2 cluster is being upgraded/migrated. This will affect all services:

- OSBv1
- OSBv2 portal
- NetPyNE
- NWBExplorer

**Comment by pgleeson** [comment]
@sanjayankur31 Can you revert/remove this at https://status.opensourcebrain.org?

**Comment by sanjayankur31** [comment]
Sure, @filippomc : all done, and fine to close this and update the status page?

**Comment by pgleeson** [comment]
Thanks @sanjayankur31!
